services:

  # Home Assistant

  wyoming-openwakeword:
    image: rhasspy/wyoming-openwakeword
    container_name: wyoming-openwakeword
    restart: unless-stopped
    ports:
      - 10400:10400
    volumes:
      - ~/homeassistant/addons/wyoming-openwakeword-custom:/custom
    command: >
      --custom-model-dir /custom
      --preload-model 'yo_bitch'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:10400"]
      interval: 30s
      timeout: 10s
      retries: 5

  wyoming-satellite:
    build: homeassistant/addons/wyoming-satellite
    container_name: wyoming-satellite
    restart: unless-stopped
    ports:
      - 10700:10700
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ~/.dots/home/.alerts:/sounds
    depends_on:
      - wyoming-openwakeword
    command: >
      --name "Main Satellite"
      --uri tcp://0.0.0.0:10700
      --mic-command 'arecord -D plughw:1,0 -r 16000 -c 1 -f S16_LE -t raw'
      --mic-seconds-to-mute-after-awake-wav 0
      --mic-noise-suppression 1
      --snd-command 'aplay -D plughw:1,0 -r 22050 -c 1 -f S16_LE -t raw'
      --snd-command-rate 22050
      --awake-wav /sounds/awake.wav
      --done-wav /sounds/done.wav
      --timer-finished-wav /sounds/timer_finished.wav

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ~/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  # Multimedia
  ### Use local IP address for the fuckarr apps

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Manila
    volumes:
      - /home/liempo/.config/deluge:/config
      - /home/liempo/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Manila
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - flaresolverr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Manila
    volumes:
      - /home/liempo/.config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - prowlarr
      - deluge
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Manila
    volumes:
      - /home/liempo/.config/sonarr:/config
      - /home/liempo/media/tv:/tv #optional
      - /home/liempo/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Manila
      - JELLYFIN_PublishedServerUrl=http://homestation.local #optional
    volumes:
      - /home/liempo/.config/jellyfin:/config
      - /home/liempo/media/tv:/data/tv
      - /home/liempo/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    restart: unless-stopped

  airport:
    container_name: airport
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    command: -o alsa 
    
