services:
  wyoming-openwakeword:
    image: rhasspy/wyoming-openwakeword
    container_name: wyoming-openwakeword
    restart: unless-stopped
    ports:
      - 10400:10400
    volumes:
      - ~/homeassistant/addons/wyoming-openwakeword-custom:/custom
    command: >
      --custom-model-dir /custom
      --preload-model 'yo_bitch'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:10400"]
      interval: 30s
      timeout: 10s
      retries: 5

  wyoming-satellite:
    build: homeassistant/addons/wyoming-satellite
    container_name: wyoming-satellite
    restart: unless-stopped
    ports:
      - 10700:10700
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ~/.dots/home/.alerts:/sounds
    depends_on:
      - wyoming-openwakeword
    command: >
      --name "Main Satellite"
      --uri tcp://0.0.0.0:10700
      --mic-command 'arecord -D plughw:1,0 -r 16000 -c 1 -f S16_LE -t raw'
      --snd-command 'aplay -D plughw:1,0 -r 22050 -c 1 -f S16_LE -t raw'
      --awake-wav /sounds/awake.wav
      --done-wav /sounds/done.wav
      --timer-finished-wav /sounds/timer_finished.wav

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ~/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host


