name: honcho

services:
  honcho_api:
    container_name: honcho_api
    build:
      context: ./src
      dockerfile: Dockerfile
    entrypoint: ["sh", "docker/entrypoint.sh"]
    depends_on:
      honcho_database:
        condition: service_healthy
      honcho_redis:
        condition: service_healthy
    ports:
      - "0.0.0.0:8000:8000"

    environment:
      - DB_CONNECTION_URI=postgresql+psycopg://postgres:postgres@honcho_database:5432/postgres
      - CACHE_URL=redis://honcho_redis:6379/0?suppress=true
      - CACHE_ENABLED=true
    env_file:
      - path: ./.env
        required: false
    restart: unless-stopped

  honcho_deriver:
    container_name: honcho_deriver
    build:
      context: ./src
      dockerfile: Dockerfile
    entrypoint: ["/app/.venv/bin/python", "-m", "src.deriver"]
    depends_on:
      honcho_database:
        condition: service_healthy
      honcho_redis:
        condition: service_healthy
    environment:
      - DB_CONNECTION_URI=postgresql+psycopg://postgres:postgres@honcho_database:5432/postgres
      - CACHE_URL=redis://honcho_redis:6379/0?suppress=true
      - CACHE_ENABLED=true
    env_file:
      - path: ./.env
        required: false
    restart: unless-stopped

  honcho_database:
    container_name: honcho_database
    image: pgvector/pgvector:pg15
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-c", "max_connections=200"]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - honcho_pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  honcho_redis:
    container_name: honcho_redis
    image: redis:8.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - honcho_redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  honcho_pgdata:
  honcho_redis_data: